apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
  namespace: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-server-data-pvc
        # SSH公開鍵をボリュームとして定義
        - name: sftp-public-key-vol
          secret:
            secretName: sftp-user-public-key
      containers:
        # ===== Minecraftコンテナ (変更なし) =====
        - name: minecraft
          image: rnagashiro/minecraft-server:latest
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: minecraft-data
              mountPath: /server/world
              subPath: world
            - name: minecraft-data
              mountPath: /server/plugins
              subPath: plugins
            # ... 他のマウントも変更なし ...

        # ===== SFTPサイドカーコンテナ (認証方法を変更) =====
        - name: sftp-server
          image: atmoz/sftp:latest
          ports:
            - containerPort: 22
          volumeMounts:
            - name: minecraft-data
              mountPath: /home/mc/data
            # 公開鍵をauthorized_keysとしてマウント
            - name: sftp-public-key-vol
              mountPath: /etc/ssh/mc/authorized_keys
              subPath: authorized_keys
              readOnly: true
          # パスワード認証を無効化し、公開鍵認証のみにする
          args:
            - "mc::0:0:::data"
