# all-in-one.yaml

# ===== 1. PersistentVolumeClaim (変更なし) =====
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-data-pvc
  namespace: mc-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# ===== 2. Minecraftサーバー用のService (変更なし) =====
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-service
  namespace: mc-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565
---
# ===== 3. SFTPサーバー用のService (変更なし) =====
apiVersion: v1
kind: Service
metadata:
  name: minecraft-sftp-service
  namespace: mc-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - name: sftp
    protocol: TCP
    port: 2222
    targetPort: 2222
---
# ===== 4. Deployment (マウントパスを統一して問題を修正) =====
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
  namespace: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-server-data-pvc

      initContainers:
      - name: init-minecraft-data
        image: rnagashiro/minecraft-server:latest # Minecraftサーバーと同じイメージを使用
        # ボリュームが空の場合にのみ、イメージ内のサーバーファイルをボリュームにコピーするコマンド
        command: ['sh', '-c', 'if [ ! -f /data/server.jar ]; then echo "Copying server files to new volume..."; cp -r /server/. /data/; else echo "Volume already has server files."; fi']
        volumeMounts:
        - name: minecraft-data
          mountPath: /data # ボリュームを/dataにマウントして中身を確認・コピー

      containers:
        # ===== Minecraftコンテナ (マウントパスとWORKDIRを修正) =====
        - name: minecraft
          image: rnagashiro/minecraft-server:latest
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
          # 修正点：マウントパスを/dataに統一します
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          # 修正点：作業ディレクトリをマウントパスに合わせます
          workingDir: /data

        # ===== SFTPサイドカーコンテナ (変更なし) =====
        - name: sftp-server
          image: lscr.io/linuxserver/openssh-server:latest
          ports:
            - containerPort: 2222
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: USER_NAME
              value: "mc"
            - name: SUDO_ACCESS
              value: "true"
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: sftp-user-pubkey-secret
                  key: PUBLIC_KEY
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
