# all-in-one.yaml

# ===== 1. PersistentVolumeClaim (変更なし) =====
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-data-pvc
  namespace: mc-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# ===== 2. Minecraftサーバー用のService (変更なし) =====
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-service
  namespace: mc-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565
---
# ===== 3. SFTPサーバー用のService (targetPortを修正) =====
apiVersion: v1
kind: Service
metadata:
  name: minecraft-sftp-service
  namespace: mc-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - name: sftp
    protocol: TCP
    port: 2222
    targetPort: 2222 # 新しいSFTPサーバーのポート番号に合わせます
---
# ===== 4. Deployment (SFTPサーバーの定義を完全に変更) =====
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
  namespace: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-server-data-pvc
        - name: sftp-public-key-vol
          secret:
            secretName: sftp-user-public-key
      containers:
        # ===== Minecraftコンテナ (変更なし) =====
        - name: minecraft
          image: rnagashiro/minecraft-server:latest
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: minecraft-data
              mountPath: /server/world
              subPath: world
            - name: minecraft-data
              mountPath: /server/plugins
              subPath: plugins
            # ... 他のマウントも変更なし ...

        # ===== SFTPサイドカーコンテナ (新しいイメージに変更) =====
        - name: sftp-server
          image: lscr.io/linuxserver/openssh-server:latest # 新しいサーバーイメージ
          ports:
            - containerPort: 2222 # このイメージは2222番ポートを使います
          env:
            - name: PUID
              value: "0" # 管理者権限(root)で実行
            - name: PGID
              value: "0" # 管理者権限(root)で実行
            - name: USER_NAME
              value: "mc" # ログインするユーザー名
            - name: SUDO_ACCESS
              value: "true" # ユーザーにsudo権限を許可
          volumeMounts:
            - name: minecraft-data
              mountPath: /data # データボリュームを/dataにマウント
            # 公開鍵を/config/keys/<ユーザー名>としてマウントします
            - name: sftp-public-key-vol
              mountPath: /config/keys/mc
              subPath: authorized_keys
