apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
  namespace: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes: # まずvolumesセクションをここに移動・定義します
        - name: minecraft-data # このボリュームを両方のコンテナで共有します
          persistentVolumeClaim:
            claimName: minecraft-server-data-pvc
      containers:
        # ===== 既存のMinecraftサーバーコンテナ =====
        - name: minecraft
          image: rnagashiro/minecraft-server:latest # CI/CDで更新されるイメージ
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: minecraft-data
              mountPath: /server/world
              subPath: world
            - name: minecraft-data
              mountPath: /server/plugins
              subPath: plugins
            - name: minecraft-data
              mountPath: /server/logs
              subPath: logs
            - name: minecraft-data
              mountPath: /server/server.properties
              subPath: server.properties
            - name: minecraft-data
              mountPath: /server/spigot.yml
              subPath: spigot.yml
            - name: minecraft-data
              mountPath: /server/ops.json
              subPath: ops.json
            - name: minecraft-data
              mountPath: /server/banned-players.json
              subPath: banned-players.json

        # ===== ここからが新しく追加するSFTPサイドカーコンテナ =====
        - name: sftp-server
          image: atmoz/sftp:latest # 定番のSFTPサーバーイメージ
          ports:
            - containerPort: 22 # SFTPのポート
          volumeMounts:
            - name: minecraft-data # Minecraftコンテナと共有するボリューム
              mountPath: /home/mc/data # ユーザーのホームディレクトリにマウント
          # 修正点: envFromをenvに変更し、より確実にSecretの値を読み込みます
          env:
            - name: SFTP_USER
              valueFrom:
                secretKeyRef:
                  name: sftp-user-credentials
                  key: SFTP_USER
            - name: SFTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sftp-user-credentials
                  key: SFTP_PASSWORD
          args:
            - $(SFTP_USER):$(SFTP_PASSWORD):0:0:::data

