# ===== 1. PersistentVolumeClaim (変更なし) =====
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-data-pvc
  namespace: mc-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# ===== 2. Minecraftサーバー用のService (変更なし) =====
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-service
  namespace: mc-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565
---
# ===== 3. SFTPサーバー用のService (変更なし) =====
apiVersion: v1
kind: Service
metadata:
  name: minecraft-sftp-service
  namespace: mc-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - name: sftp
    protocol: TCP
    port: 2222
    targetPort: 22
---
# ===== 4. Deployment (securityContextを追加してファイル権限を修正) =====
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
  namespace: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      # 修正点：securityContextを追加して、マウントされたファイルのグループ権限をroot(0)に設定します
      securityContext:
        fsGroup: 0
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-server-data-pvc
        - name: sftp-public-key-vol
          secret:
            secretName: sftp-user-public-key
      containers:
        # ===== Minecraftコンテナ (変更なし) =====
        - name: minecraft
          image: rnagashiro/minecraft-server:latest
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: minecraft-data
              mountPath: /server/world
              subPath: world
            - name: minecraft-data
              mountPath: /server/plugins
              subPath: plugins
            # ... 他のマウントも変更なし ...

        # ===== SFTPサイドカーコンテナ (変更なし) =====
        - name: sftp-server
          image: atmoz/sftp:latest
          ports:
            - containerPort: 22
          volumeMounts:
            - name: minecraft-data
              mountPath: /home/mc/data
            - name: sftp-public-key-vol
              mountPath: /home/mc/.ssh/authorized_keys
              subPath: authorized_keys
              readOnly: true
          args:
            - "mc::0:0:::data"
