apiVersion: v1
kind: Service
metadata:
  name: minecraft-sftp-service
  namespace: mc-server
spec:
  type: NodePort # NodePortタイプで外部にポートを公開します
  selector:
    app: minecraft-server # 同じPodを選択します
  ports:
    - name: sftp
      protocol: TCP
      port: 2222 # クラスタ内でのポート
      targetPort: 22 # コンテナのSFTPポート(22)に転送
      # NodePortを指定しない場合、30000-32767の範囲で自動的に割り当てられます
