apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-service
  namespace: mc-server
spec:
  type: LoadBalancer # クラウド環境ならこれが一番簡単。外部IPが自動で割り当てられます。
  # もしLoadBalancerが使えない環境（k3sなど）なら type: NodePort を使う
  selector:
    app: minecraft-server # このラベルを持つPodにトラフィックを流す
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 25565