apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-service
  namespace: mc-server
spec:
  type: LoadBalancer # このタイプは変更なし
  selector:
    app: minecraft-server
  ports:
  # ===== 既存のMinecraft用ポート設定 =====
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565
  # ===== ここからが新しく追加するSFTP用ポート設定 =====
  - name: sftp
    protocol: TCP
    port: 2222 # 外部からアクセスするポート番号
    targetPort: 22  # SFTPコンテナのポート番号
