apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample # 前に作ったのと同じ名前か、新しい名前にする
  namespace: default # デプロイする名前空間 (defaultでええやろ)
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - name: nginx
        image: nginx:latest # 最新のnginxイメージ
        ports:
        - containerPort: 80 # コンテナのポート80を公開
        resources:
          requests:
            memory: "64Mi" # メモリのリクエスト
            cpu: "250m" # CPUのリクエスト
          limits:
            memory: "128Mi" # メモリの制限
            cpu: "500m" # CPUの制限