# replicaCount: 3 # これはPod全体の数

# PHP-FPMコンテナ用のイメージ設定
phpFpmImage:
  repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.PHP_FPM_IMAGE_NAME }} # CIで使うフルパスを書いてもええし、
  # ArgoCD側で上書きするならリポジトリ名だけでもOK
  pullPolicy: IfNotPresent
  tag: "6d3349f" # ← CIがここを書き換える
# Nginxコンテナ用のイメージ設定 (もしNginxもカスタムイメージなら)
nginxImage:
  repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.NGINX_IMAGE_NAME }}
  pullPolicy: IfNotPresent
  tag: "6d3349f" # ← CIがここを書き換える (もしNginxイメージもCIで作るなら)
# serviceAccount: ... (省略) ...
# service: ... (省略) ...
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: nqg1t0.com # または argocd.nqg1t0.com とか、アプリのドメイン
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: my-app-tls-prod # アプリ用のSecret名
      hosts:
        - nqg1t0.com # アプリ用のドメイン
# ... (resources以下省略) ...

image:
  tag: dbeb92f
