{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      # ★★★ ここからが修正部分 ★★★
      # このPodと、Podがマウントするボリュームのセキュリティ設定
      {{- if .Values.postgresql.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.postgresql.podSecurityContext.fsGroup }}
      {{- end }}
      # PostgreSQLコンテナが起動する前に、このinitContainerで権限を強制設定
      initContainers:
      - name: chmod-data-dir
        image: busybox:1.36
        command: ["sh", "-c", "chmod -R 777 /var/lib/postgresql/data"]
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      # ★★★ ここまでが修正部分 ★★★
      containers:
        - name: postgres
          image: "postgres:16"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-postgres-secret
          {{- if .Values.postgresql.persistence.enabled }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          {{- end }}
      {{- if .Values.postgresql.persistence.enabled }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
      {{- end }}
{{- end }}
